/**
 * Default Saudi chart of accounts (4 levels: 1-digit class, 2-digit group, 4-digit
 * sub-group, 6-digit posting account). `key` marks accounts the posting engine
 * resolves by role, so users may rename/renumber accounts freely.
 */
type Row = [code: string, nameAr: string, nameEn: string, subtype: string, opts?: { key?: string; cash?: boolean; system?: boolean }];

export const SAUDI_COA: Row[] = [
  ["1", "الأصول", "Assets", "ASSET"],
  ["11", "الأصول المتداولة", "Current Assets", "CURRENT_ASSET"],
  ["1101", "النقدية بالصناديق", "Cash on Hand", "CASH"],
  ["110101", "الصندوق الرئيسي", "Main Cash", "CASH", { key: "CASH", cash: true }],
  ["110102", "صندوق نقاط البيع", "POS Cash Drawer", "CASH", { key: "POS_CASH", cash: true }],
  ["110103", "العهد النقدية", "Petty Cash", "CASH", { cash: true }],
  ["1102", "النقدية لدى البنوك", "Cash at Banks", "BANK"],
  ["110201", "البنك الأهلي السعودي", "SNB Bank", "BANK", { key: "BANK", cash: true }],
  ["110202", "مصرف الراجحي", "Al Rajhi Bank", "BANK", { cash: true }],
  ["110203", "حساب تسوية مدى والبطاقات", "Mada / Card Clearing", "BANK", { key: "CARD_CLEARING", cash: true }],
  ["1103", "الذمم المدينة", "Receivables", "RECEIVABLE"],
  ["110301", "العملاء", "Accounts Receivable", "RECEIVABLE", { key: "AR" }],
  ["110302", "أوراق القبض (شيكات مستلمة)", "Notes Receivable", "RECEIVABLE", { key: "NOTES_REC" }],
  ["110303", "سلف وعهد الموظفين", "Employee Advances", "CURRENT_ASSET"],
  ["110304", "مخصص الديون المشكوك في تحصيلها", "Allowance for Doubtful Debts", "RECEIVABLE"],
  ["1104", "المخزون", "Inventory", "INVENTORY"],
  ["110401", "مخزون البضائع", "Merchandise Inventory", "INVENTORY", { key: "INVENTORY" }],
  ["1105", "أرصدة مدينة أخرى", "Other Debit Balances", "CURRENT_ASSET"],
  ["110501", "مصروفات مدفوعة مقدماً", "Prepaid Expenses", "CURRENT_ASSET"],
  ["110502", "ضريبة القيمة المضافة - المدخلات", "Input VAT", "CURRENT_ASSET", { key: "VAT_IN" }],
  ["110503", "دفعات مقدمة للموردين", "Advances to Suppliers", "CURRENT_ASSET"],
  ["12", "الأصول غير المتداولة", "Non-current Assets", "FIXED_ASSET"],
  ["1201", "الممتلكات والمعدات", "Property & Equipment", "FIXED_ASSET"],
  ["120101", "الأراضي", "Land", "FIXED_ASSET"],
  ["120102", "المباني", "Buildings", "FIXED_ASSET"],
  ["120103", "السيارات ووسائل النقل", "Vehicles", "FIXED_ASSET"],
  ["120104", "الأثاث والمفروشات", "Furniture & Fixtures", "FIXED_ASSET"],
  ["120105", "الأجهزة والمعدات", "Equipment", "FIXED_ASSET", { key: "FIXED_ASSET" }],
  ["120106", "أجهزة الحاسب الآلي", "Computers", "FIXED_ASSET"],
  ["1202", "مجمع الإهلاك", "Accumulated Depreciation", "ACC_DEPRECIATION"],
  ["120201", "مجمع إهلاك المباني", "Acc. Dep. Buildings", "ACC_DEPRECIATION"],
  ["120202", "مجمع إهلاك السيارات", "Acc. Dep. Vehicles", "ACC_DEPRECIATION"],
  ["120203", "مجمع إهلاك الأثاث", "Acc. Dep. Furniture", "ACC_DEPRECIATION"],
  ["120204", "مجمع إهلاك الأجهزة والمعدات", "Acc. Dep. Equipment", "ACC_DEPRECIATION", { key: "ACC_DEP" }],
  ["120205", "مجمع إهلاك الحاسب الآلي", "Acc. Dep. Computers", "ACC_DEPRECIATION"],

  ["2", "الخصوم", "Liabilities", "CURRENT_LIABILITY"],
  ["21", "الخصوم المتداولة", "Current Liabilities", "CURRENT_LIABILITY"],
  ["2101", "الذمم الدائنة", "Payables", "PAYABLE"],
  ["210101", "الموردون", "Accounts Payable", "PAYABLE", { key: "AP" }],
  ["210102", "أوراق الدفع (شيكات صادرة)", "Notes Payable", "PAYABLE", { key: "NOTES_PAY" }],
  ["210103", "دفعات مقدمة من العملاء", "Customer Advances", "CURRENT_LIABILITY"],
  ["2102", "الضرائب والزكاة", "Taxes & Zakat", "TAX"],
  ["210201", "ضريبة القيمة المضافة - المخرجات", "Output VAT", "TAX", { key: "VAT_OUT" }],
  ["210202", "ضريبة القيمة المضافة - مستحقة للهيئة", "VAT Payable (Settlement)", "TAX", { key: "VAT_PAYABLE" }],
  ["210203", "مخصص الزكاة", "Zakat Provision", "TAX", { key: "ZAKAT_PAYABLE" }],
  ["2103", "مستحقات وأرصدة دائنة أخرى", "Accruals & Other Credits", "CURRENT_LIABILITY"],
  ["210301", "رواتب وأجور مستحقة", "Salaries Payable", "CURRENT_LIABILITY", { key: "SALARIES_PAYABLE" }],
  ["210302", "التأمينات الاجتماعية المستحقة", "GOSI Payable", "CURRENT_LIABILITY"],
  ["210303", "مصروفات مستحقة", "Accrued Expenses", "CURRENT_LIABILITY"],
  ["22", "الخصوم غير المتداولة", "Non-current Liabilities", "LONG_TERM_LIABILITY"],
  ["2201", "مخصص مكافأة نهاية الخدمة", "End of Service Provision", "LONG_TERM_LIABILITY"],
  ["2202", "قروض طويلة الأجل", "Long-term Loans", "LONG_TERM_LIABILITY"],

  ["3", "حقوق الملكية", "Equity", "EQUITY"],
  ["31", "رأس المال والاحتياطيات", "Capital & Reserves", "EQUITY"],
  ["3101", "رأس المال", "Share Capital", "CAPITAL", { key: "CAPITAL" }],
  ["3102", "الاحتياطي النظامي", "Statutory Reserve", "EQUITY"],
  ["3103", "جاري المالك / الشركاء", "Owner Current Account", "EQUITY", { key: "OWNER_CURRENT" }],
  ["3104", "الأرباح (الخسائر) المبقاة", "Retained Earnings", "RETAINED", { key: "RETAINED" }],
  ["3105", "أرصدة افتتاحية", "Opening Balance Equity", "EQUITY", { key: "OPENING_EQUITY" }],

  ["4", "الإيرادات", "Revenue", "SALES"],
  ["41", "إيرادات النشاط", "Operating Revenue", "SALES"],
  ["4101", "المبيعات", "Sales", "SALES", { key: "SALES" }],
  ["4102", "إيرادات الخدمات", "Service Revenue", "SALES", { key: "SERVICE_REVENUE" }],
  ["4103", "مردودات ومسموحات المبيعات", "Sales Returns & Allowances", "SALES_RETURNS", { key: "SALES_RETURNS" }],
  ["42", "إيرادات أخرى", "Other Income", "OTHER_INCOME"],
  ["4201", "أرباح فروقات الجرد", "Inventory Count Gains", "OTHER_INCOME", { key: "INV_GAIN" }],
  ["4202", "إيرادات متنوعة", "Miscellaneous Income", "OTHER_INCOME", { key: "OTHER_INCOME" }],

  ["5", "المصروفات والتكاليف", "Expenses", "EXPENSE"],
  ["51", "تكلفة المبيعات", "Cost of Sales", "COGS"],
  ["5101", "تكلفة البضاعة المباعة", "Cost of Goods Sold", "COGS", { key: "COGS" }],
  ["5102", "عجز وتالف المخزون", "Inventory Shrinkage", "COGS", { key: "INV_LOSS" }],
  ["5103", "مشتريات خدمات مباشرة", "Direct Service Purchases", "COGS", { key: "PURCHASE_EXPENSE" }],
  ["52", "المصروفات العمومية والإدارية", "General & Administrative", "EXPENSE"],
  ["5201", "الرواتب والأجور", "Salaries & Wages", "EXPENSE", { key: "SALARIES" }],
  ["5202", "بدلات ومزايا الموظفين", "Allowances & Benefits", "EXPENSE"],
  ["5203", "التأمينات الاجتماعية", "GOSI Expense", "EXPENSE"],
  ["5204", "الإيجارات", "Rent", "EXPENSE", { key: "RENT" }],
  ["5205", "الكهرباء والمياه", "Utilities", "EXPENSE", { key: "UTILITIES" }],
  ["5206", "الاتصالات والإنترنت", "Telecom & Internet", "EXPENSE"],
  ["5207", "القرطاسية والمطبوعات", "Stationery & Printing", "EXPENSE"],
  ["5208", "الصيانة والإصلاح", "Repairs & Maintenance", "EXPENSE"],
  ["5209", "رسوم حكومية واشتراكات", "Government Fees", "EXPENSE", { key: "GOV_FEES" }],
  ["5210", "أتعاب مهنية واستشارات", "Professional Fees", "EXPENSE"],
  ["5211", "عمولات ومصروفات بنكية", "Bank Charges", "EXPENSE", { key: "BANK_FEES" }],
  ["5212", "مصروف الإهلاك", "Depreciation Expense", "EXPENSE", { key: "DEPRECIATION" }],
  ["5213", "مصروفات عمومية متنوعة", "Miscellaneous Expenses", "EXPENSE", { key: "GENERAL_EXPENSE" }],
  ["5214", "عجز وزيادة الصندوق", "Cash Over / Short", "EXPENSE", { key: "CASH_DIFF" }],
  ["53", "مصروفات البيع والتسويق", "Selling & Marketing", "SELLING_EXPENSE"],
  ["5301", "الدعاية والإعلان", "Advertising", "SELLING_EXPENSE", { key: "ADVERTISING" }],
  ["5302", "عمولات المبيعات", "Sales Commissions", "SELLING_EXPENSE"],
  ["5303", "مصروفات النقل والتوصيل", "Delivery & Freight", "SELLING_EXPENSE"],
  ["54", "مصروفات أخرى", "Other Expenses", "OTHER_EXPENSE"],
  ["5401", "الزكاة الشرعية", "Zakat Expense", "ZAKAT", { key: "ZAKAT" }],
  ["5402", "مصروفات تمويلية", "Finance Costs", "OTHER_EXPENSE"],
  ["5403", "خسائر بيع أصول", "Loss on Asset Disposal", "OTHER_EXPENSE"],
];

export const TYPE_BY_CLASS: Record<string, string> = { "1": "ASSET", "2": "LIABILITY", "3": "EQUITY", "4": "REVENUE", "5": "EXPENSE" };

/** Natural balance side for display: assets & expenses are debit-natured. */
export const debitNature = (type: string) => type === "ASSET" || type === "EXPENSE";

export const SUBTYPE_AR: Record<string, string> = {
  CASH: "نقدية", BANK: "بنوك", RECEIVABLE: "ذمم مدينة", INVENTORY: "مخزون", CURRENT_ASSET: "أصول متداولة أخرى",
  FIXED_ASSET: "أصول ثابتة", ACC_DEPRECIATION: "مجمع إهلاك", PAYABLE: "ذمم دائنة", TAX: "ضرائب وزكاة",
  CURRENT_LIABILITY: "خصوم متداولة أخرى", LONG_TERM_LIABILITY: "خصوم طويلة الأجل", CAPITAL: "رأس المال",
  RETAINED: "أرباح مبقاة", EQUITY: "حقوق ملكية أخرى", SALES: "مبيعات", SALES_RETURNS: "مردودات مبيعات",
  OTHER_INCOME: "إيرادات أخرى", COGS: "تكلفة مبيعات", EXPENSE: "مصروفات عمومية وإدارية",
  SELLING_EXPENSE: "مصروفات بيع وتسويق", OTHER_EXPENSE: "مصروفات أخرى", ZAKAT: "زكاة", ASSET: "أصول",
};
